#
# This R-script has been generated by createRDatabaseInterface
# at: Thu Mar 02 15:46:55 2017
#

# odm_Categories ---------------------------------------------------------------
odm_Categories <- function # select records from Categories
### select and filter records from Categories
(
  where = NULL,
  ### WHERE condition
  where_VariableID = NA,
  ### condition for field \emph{VariableID}: Integer identifier that references the Variables record of a categorical variable.
  where_DataValue = NA,
  ### condition for field \emph{DataValue}: Numeric value that defines the category
  where_CategoryDescription = NA,
  ### condition for field \emph{CategoryDescription}: Definition of categorical variable value
  select = NULL,
  ### fields/expressions to select
  select_VariableID = NA,
  ### select field \emph{VariableID}?
  select_DataValue = NA,
  ### select field \emph{DataValue}?
  select_CategoryDescription = NA,
  ### select field \emph{CategoryDescription}?
  orderBy = NULL,
  ### ORDER BY clause of SQL expression
  orderBy_VariableID = NA,
  ### order by field \emph{VariableID}?
  orderBy_DataValue = NA,
  ### order by field \emph{DataValue}?
  orderBy_CategoryDescription = NA,
  ### order by field \emph{CategoryDescription}?
  db = currentDb(),
  ...
  ### additional arguments passed to \code{\link{selectFromTable}}
) 
{
  arguments <- list(
    select = select,
    select_VariableID = select_VariableID,
    select_DataValue = select_DataValue,
    select_CategoryDescription = select_CategoryDescription ,
    where = where,
    where_VariableID = where_VariableID,
    where_DataValue = where_DataValue,
    where_CategoryDescription = where_CategoryDescription ,
    orderBy = orderBy,
    orderBy_VariableID = orderBy_VariableID,
    orderBy_DataValue = orderBy_DataValue,
    orderBy_CategoryDescription = orderBy_CategoryDescription
  )

  selectFromTable(db, 'Categories', arguments, ...)
}

# odm_CensorCodeCV -------------------------------------------------------------
odm_CensorCodeCV <- function # select records from CensorCodeCV
### select and filter records from CensorCodeCV
(
  where = NULL,
  ### WHERE condition
  where_Term = NA,
  ### condition for field \emph{Term}: Controlled vocabulary for CensorCode
  where_Definition = NA,
  ### condition for field \emph{Definition}: Definition of CensorCode controlled vocabulary term. The Definition is optional if the term is self explanatory.
  select = NULL,
  ### fields/expressions to select
  select_Term = NA,
  ### select field \emph{Term}?
  select_Definition = NA,
  ### select field \emph{Definition}?
  orderBy = NULL,
  ### ORDER BY clause of SQL expression
  orderBy_Term = NA,
  ### order by field \emph{Term}?
  orderBy_Definition = NA,
  ### order by field \emph{Definition}?
  db = currentDb(),
  ...
  ### additional arguments passed to \code{\link{selectFromTable}}
) 
{
  arguments <- list(
    select = select,
    select_Term = select_Term,
    select_Definition = select_Definition ,
    where = where,
    where_Term = where_Term,
    where_Definition = where_Definition ,
    orderBy = orderBy,
    orderBy_Term = orderBy_Term,
    orderBy_Definition = orderBy_Definition
  )

  selectFromTable(db, 'CensorCodeCV', arguments, ...)
}

# odm_DataTypeCV ---------------------------------------------------------------
odm_DataTypeCV <- function # select records from DataTypeCV
### select and filter records from DataTypeCV
(
  where = NULL,
  ### WHERE condition
  where_Term = NA,
  ### condition for field \emph{Term}: Controlled vocabulary for DataType
  where_Definition = NA,
  ### condition for field \emph{Definition}: Definition of DataType controlled vocabulary term. The Definition is optional if the term is self explanatory.
  select = NULL,
  ### fields/expressions to select
  select_Term = NA,
  ### select field \emph{Term}?
  select_Definition = NA,
  ### select field \emph{Definition}?
  orderBy = NULL,
  ### ORDER BY clause of SQL expression
  orderBy_Term = NA,
  ### order by field \emph{Term}?
  orderBy_Definition = NA,
  ### order by field \emph{Definition}?
  db = currentDb(),
  ...
  ### additional arguments passed to \code{\link{selectFromTable}}
) 
{
  arguments <- list(
    select = select,
    select_Term = select_Term,
    select_Definition = select_Definition ,
    where = where,
    where_Term = where_Term,
    where_Definition = where_Definition ,
    orderBy = orderBy,
    orderBy_Term = orderBy_Term,
    orderBy_Definition = orderBy_Definition
  )

  selectFromTable(db, 'DataTypeCV', arguments, ...)
}

# odm_DataValues ---------------------------------------------------------------
odm_DataValues <- function # select records from DataValues
### select and filter records from DataValues
(
  where = NULL,
  ### WHERE condition
  where_ValueID = NA,
  ### condition for field \emph{ValueID}: Unique integer identifier for each data value.
  where_DataValue = NA,
  ### condition for field \emph{DataValue}: The numeric value of the observation. For Categorical variables, a number is stored her. The Variables table has DataType as Categorical and the Categories table maps from the DataValue onto Category Description
  where_ValueAccuracy = NA,
  ### condition for field \emph{ValueAccuracy}: Numeric value that describes the measurement accuracy of the data value. If not given, it is interpreted as unknown.
  where_LocalDateTime = NA,
  ### condition for field \emph{LocalDateTime}: Local date and time at which the data value was observed. Represented in an implementation specific format.
  where_UTCOffset = NA,
  ### condition for field \emph{UTCOffset}: Offset in hours from UTC time of the corresponding LocalDateTime value.
  where_DateTimeUTC = NA,
  ### condition for field \emph{DateTimeUTC}: Universal UTC date and time at which the data value was observed. Represented in an implementation specific format.
  where_SiteID = NA,
  ### condition for field \emph{SiteID}: Integer identifier that references the site at which the observation was measured. This links data values to their locations in the Sites table.
  where_VariableID = NA,
  ### condition for field \emph{VariableID}: Integer identifier that references the variable that was measured. This links data values to their variable in the Variables table.
  where_OffsetValue = NA,
  ### condition for field \emph{OffsetValue}: Distance from a datum or control point to the point at which a data value was observed. If not given the OffsetValue is inferred to be 0, or not relevant/necessary.
  where_OffsetTypeID = NA,
  ### condition for field \emph{OffsetTypeID}: Integer identifier that references the measurement offset type in the OffsetTypes table.
  where_CensorCode = NA,
  ### condition for field \emph{CensorCode}: Text indication of whether the data value is censored from the CensorCodeCV controlled vocabulary.
  where_QualifierID = NA,
  ### condition for field \emph{QualifierID}: Integer identifier that references the Qualifiers table. If Null, the data value is inferred to not be qualified.
  where_MethodID = NA,
  ### condition for field \emph{MethodID}: Integer identifier that references method used to generate the data value in the Methods table.
  where_SourceID = NA,
  ### condition for field \emph{SourceID}: Integer identifier that references the record in the Sources table giving the source of the data value.
  where_SampleID = NA,
  ### condition for field \emph{SampleID}: Integer identifier that references into the Samples table. This is required only if the data value resulted from a physical sample processed in a lab.
  where_DerivedFromID = NA,
  ### condition for field \emph{DerivedFromID}: Integer identifier for the derived from group of data values that the current data value is derived from. This refers to a group of derived from records in the DerivedFrom table. If NULL, the data value is inferred to not be derived from another data value.
  where_QualityControlLevelID = NA,
  ### condition for field \emph{QualityControlLevelID}: Integer identifier giving the level of quality control that the value has been subjected to. This references the QualityControlLevels table.
  select = NULL,
  ### fields/expressions to select
  select_ValueID = NA,
  ### select field \emph{ValueID}?
  select_DataValue = NA,
  ### select field \emph{DataValue}?
  select_ValueAccuracy = NA,
  ### select field \emph{ValueAccuracy}?
  select_LocalDateTime = NA,
  ### select field \emph{LocalDateTime}?
  select_UTCOffset = NA,
  ### select field \emph{UTCOffset}?
  select_DateTimeUTC = NA,
  ### select field \emph{DateTimeUTC}?
  select_SiteID = NA,
  ### select field \emph{SiteID}?
  select_VariableID = NA,
  ### select field \emph{VariableID}?
  select_OffsetValue = NA,
  ### select field \emph{OffsetValue}?
  select_OffsetTypeID = NA,
  ### select field \emph{OffsetTypeID}?
  select_CensorCode = NA,
  ### select field \emph{CensorCode}?
  select_QualifierID = NA,
  ### select field \emph{QualifierID}?
  select_MethodID = NA,
  ### select field \emph{MethodID}?
  select_SourceID = NA,
  ### select field \emph{SourceID}?
  select_SampleID = NA,
  ### select field \emph{SampleID}?
  select_DerivedFromID = NA,
  ### select field \emph{DerivedFromID}?
  select_QualityControlLevelID = NA,
  ### select field \emph{QualityControlLevelID}?
  orderBy = NULL,
  ### ORDER BY clause of SQL expression
  orderBy_ValueID = NA,
  ### order by field \emph{ValueID}?
  orderBy_DataValue = NA,
  ### order by field \emph{DataValue}?
  orderBy_ValueAccuracy = NA,
  ### order by field \emph{ValueAccuracy}?
  orderBy_LocalDateTime = NA,
  ### order by field \emph{LocalDateTime}?
  orderBy_UTCOffset = NA,
  ### order by field \emph{UTCOffset}?
  orderBy_DateTimeUTC = NA,
  ### order by field \emph{DateTimeUTC}?
  orderBy_SiteID = NA,
  ### order by field \emph{SiteID}?
  orderBy_VariableID = NA,
  ### order by field \emph{VariableID}?
  orderBy_OffsetValue = NA,
  ### order by field \emph{OffsetValue}?
  orderBy_OffsetTypeID = NA,
  ### order by field \emph{OffsetTypeID}?
  orderBy_CensorCode = NA,
  ### order by field \emph{CensorCode}?
  orderBy_QualifierID = NA,
  ### order by field \emph{QualifierID}?
  orderBy_MethodID = NA,
  ### order by field \emph{MethodID}?
  orderBy_SourceID = NA,
  ### order by field \emph{SourceID}?
  orderBy_SampleID = NA,
  ### order by field \emph{SampleID}?
  orderBy_DerivedFromID = NA,
  ### order by field \emph{DerivedFromID}?
  orderBy_QualityControlLevelID = NA,
  ### order by field \emph{QualityControlLevelID}?
  db = currentDb(),
  ...
  ### additional arguments passed to \code{\link{selectFromTable}}
) 
{
  arguments <- list(
    select = select,
    select_ValueID = select_ValueID,
    select_DataValue = select_DataValue,
    select_ValueAccuracy = select_ValueAccuracy,
    select_LocalDateTime = select_LocalDateTime,
    select_UTCOffset = select_UTCOffset,
    select_DateTimeUTC = select_DateTimeUTC,
    select_SiteID = select_SiteID,
    select_VariableID = select_VariableID,
    select_OffsetValue = select_OffsetValue,
    select_OffsetTypeID = select_OffsetTypeID,
    select_CensorCode = select_CensorCode,
    select_QualifierID = select_QualifierID,
    select_MethodID = select_MethodID,
    select_SourceID = select_SourceID,
    select_SampleID = select_SampleID,
    select_DerivedFromID = select_DerivedFromID,
    select_QualityControlLevelID = select_QualityControlLevelID ,
    where = where,
    where_ValueID = where_ValueID,
    where_DataValue = where_DataValue,
    where_ValueAccuracy = where_ValueAccuracy,
    where_LocalDateTime = where_LocalDateTime,
    where_UTCOffset = where_UTCOffset,
    where_DateTimeUTC = where_DateTimeUTC,
    where_SiteID = where_SiteID,
    where_VariableID = where_VariableID,
    where_OffsetValue = where_OffsetValue,
    where_OffsetTypeID = where_OffsetTypeID,
    where_CensorCode = where_CensorCode,
    where_QualifierID = where_QualifierID,
    where_MethodID = where_MethodID,
    where_SourceID = where_SourceID,
    where_SampleID = where_SampleID,
    where_DerivedFromID = where_DerivedFromID,
    where_QualityControlLevelID = where_QualityControlLevelID ,
    orderBy = orderBy,
    orderBy_ValueID = orderBy_ValueID,
    orderBy_DataValue = orderBy_DataValue,
    orderBy_ValueAccuracy = orderBy_ValueAccuracy,
    orderBy_LocalDateTime = orderBy_LocalDateTime,
    orderBy_UTCOffset = orderBy_UTCOffset,
    orderBy_DateTimeUTC = orderBy_DateTimeUTC,
    orderBy_SiteID = orderBy_SiteID,
    orderBy_VariableID = orderBy_VariableID,
    orderBy_OffsetValue = orderBy_OffsetValue,
    orderBy_OffsetTypeID = orderBy_OffsetTypeID,
    orderBy_CensorCode = orderBy_CensorCode,
    orderBy_QualifierID = orderBy_QualifierID,
    orderBy_MethodID = orderBy_MethodID,
    orderBy_SourceID = orderBy_SourceID,
    orderBy_SampleID = orderBy_SampleID,
    orderBy_DerivedFromID = orderBy_DerivedFromID,
    orderBy_QualityControlLevelID = orderBy_QualityControlLevelID
  )

  selectFromTable(db, 'DataValues', arguments, ...)
}

# odm_DerivedFrom --------------------------------------------------------------
odm_DerivedFrom <- function # select records from DerivedFrom
### select and filter records from DerivedFrom
(
  where = NULL,
  ### WHERE condition
  where_DerivedFromID = NA,
  ### condition for field \emph{DerivedFromID}: Integer identifying the group of data values from which a quantity is derived.
  where_ValueID = NA,
  ### condition for field \emph{ValueID}: Integer identifier referencing data values that comprise a group from which a quantity is derived. This corresponds to ValueID in the DataValues table.
  select = NULL,
  ### fields/expressions to select
  select_DerivedFromID = NA,
  ### select field \emph{DerivedFromID}?
  select_ValueID = NA,
  ### select field \emph{ValueID}?
  orderBy = NULL,
  ### ORDER BY clause of SQL expression
  orderBy_DerivedFromID = NA,
  ### order by field \emph{DerivedFromID}?
  orderBy_ValueID = NA,
  ### order by field \emph{ValueID}?
  db = currentDb(),
  ...
  ### additional arguments passed to \code{\link{selectFromTable}}
) 
{
  arguments <- list(
    select = select,
    select_DerivedFromID = select_DerivedFromID,
    select_ValueID = select_ValueID ,
    where = where,
    where_DerivedFromID = where_DerivedFromID,
    where_ValueID = where_ValueID ,
    orderBy = orderBy,
    orderBy_DerivedFromID = orderBy_DerivedFromID,
    orderBy_ValueID = orderBy_ValueID
  )

  selectFromTable(db, 'DerivedFrom', arguments, ...)
}

# odm_GeneralCategoryCV --------------------------------------------------------
odm_GeneralCategoryCV <- function # select records from GeneralCategoryCV
### select and filter records from GeneralCategoryCV
(
  where = NULL,
  ### WHERE condition
  where_Term = NA,
  ### condition for field \emph{Term}: Controlled vocabulary for GeneralCategory.
  where_Definition = NA,
  ### condition for field \emph{Definition}: Definition of GeneralCategory controlled vocabulary term. The definition is optional if the term is self explanatory.
  select = NULL,
  ### fields/expressions to select
  select_Term = NA,
  ### select field \emph{Term}?
  select_Definition = NA,
  ### select field \emph{Definition}?
  orderBy = NULL,
  ### ORDER BY clause of SQL expression
  orderBy_Term = NA,
  ### order by field \emph{Term}?
  orderBy_Definition = NA,
  ### order by field \emph{Definition}?
  db = currentDb(),
  ...
  ### additional arguments passed to \code{\link{selectFromTable}}
) 
{
  arguments <- list(
    select = select,
    select_Term = select_Term,
    select_Definition = select_Definition ,
    where = where,
    where_Term = where_Term,
    where_Definition = where_Definition ,
    orderBy = orderBy,
    orderBy_Term = orderBy_Term,
    orderBy_Definition = orderBy_Definition
  )

  selectFromTable(db, 'GeneralCategoryCV', arguments, ...)
}

# odm_GroupDescriptions --------------------------------------------------------
odm_GroupDescriptions <- function # select records from GroupDescriptions
### select and filter records from GroupDescriptions
(
  where = NULL,
  ### WHERE condition
  where_GroupID = NA,
  ### condition for field \emph{GroupID}: Unique integer identifier for each group of data values that has been formed. This also references to GroupID in the Groups table.
  where_GroupDescription = NA,
  ### condition for field \emph{GroupDescription}: Text description of the group.
  select = NULL,
  ### fields/expressions to select
  select_GroupID = NA,
  ### select field \emph{GroupID}?
  select_GroupDescription = NA,
  ### select field \emph{GroupDescription}?
  orderBy = NULL,
  ### ORDER BY clause of SQL expression
  orderBy_GroupID = NA,
  ### order by field \emph{GroupID}?
  orderBy_GroupDescription = NA,
  ### order by field \emph{GroupDescription}?
  db = currentDb(),
  ...
  ### additional arguments passed to \code{\link{selectFromTable}}
) 
{
  arguments <- list(
    select = select,
    select_GroupID = select_GroupID,
    select_GroupDescription = select_GroupDescription ,
    where = where,
    where_GroupID = where_GroupID,
    where_GroupDescription = where_GroupDescription ,
    orderBy = orderBy,
    orderBy_GroupID = orderBy_GroupID,
    orderBy_GroupDescription = orderBy_GroupDescription
  )

  selectFromTable(db, 'GroupDescriptions', arguments, ...)
}

# odm_Groups -------------------------------------------------------------------
odm_Groups <- function # select records from Groups
### select and filter records from Groups
(
  where = NULL,
  ### WHERE condition
  where_GroupID = NA,
  ### condition for field \emph{GroupID}: Integer ID for each group of data values that has been formed.
  where_ValueID = NA,
  ### condition for field \emph{ValueID}: Integer identifier for each data value that belongs to a group. This corresponds to ValueID in the DataValues table
  select = NULL,
  ### fields/expressions to select
  select_GroupID = NA,
  ### select field \emph{GroupID}?
  select_ValueID = NA,
  ### select field \emph{ValueID}?
  orderBy = NULL,
  ### ORDER BY clause of SQL expression
  orderBy_GroupID = NA,
  ### order by field \emph{GroupID}?
  orderBy_ValueID = NA,
  ### order by field \emph{ValueID}?
  db = currentDb(),
  ...
  ### additional arguments passed to \code{\link{selectFromTable}}
) 
{
  arguments <- list(
    select = select,
    select_GroupID = select_GroupID,
    select_ValueID = select_ValueID ,
    where = where,
    where_GroupID = where_GroupID,
    where_ValueID = where_ValueID ,
    orderBy = orderBy,
    orderBy_GroupID = orderBy_GroupID,
    orderBy_ValueID = orderBy_ValueID
  )

  selectFromTable(db, 'Groups', arguments, ...)
}

# odm_ISOMetadata --------------------------------------------------------------
odm_ISOMetadata <- function # select records from ISOMetadata
### select and filter records from ISOMetadata
(
  where = NULL,
  ### WHERE condition
  where_MetadataID = NA,
  ### condition for field \emph{MetadataID}: Unique integer ID for each metadata record.
  where_TopicCategory = NA,
  ### condition for field \emph{TopicCategory}: Topic category keyword that gives the broad ISO19115 metadata topic category for data from this source. The controlled vocabulary of topic category keywords is given in the TopicCategoryCV table.
  where_Title = NA,
  ### condition for field \emph{Title}: Title of data from a specific data source.
  where_Abstract = NA,
  ### condition for field \emph{Abstract}: Abstract of data from a specific data source.
  where_ProfileVersion = NA,
  ### condition for field \emph{ProfileVersion}: Name of metadata profile used by the data source
  where_MetadataLink = NA,
  ### condition for field \emph{MetadataLink}: Link to additional metadata reference material.
  select = NULL,
  ### fields/expressions to select
  select_MetadataID = NA,
  ### select field \emph{MetadataID}?
  select_TopicCategory = NA,
  ### select field \emph{TopicCategory}?
  select_Title = NA,
  ### select field \emph{Title}?
  select_Abstract = NA,
  ### select field \emph{Abstract}?
  select_ProfileVersion = NA,
  ### select field \emph{ProfileVersion}?
  select_MetadataLink = NA,
  ### select field \emph{MetadataLink}?
  orderBy = NULL,
  ### ORDER BY clause of SQL expression
  orderBy_MetadataID = NA,
  ### order by field \emph{MetadataID}?
  orderBy_TopicCategory = NA,
  ### order by field \emph{TopicCategory}?
  orderBy_Title = NA,
  ### order by field \emph{Title}?
  orderBy_Abstract = NA,
  ### order by field \emph{Abstract}?
  orderBy_ProfileVersion = NA,
  ### order by field \emph{ProfileVersion}?
  orderBy_MetadataLink = NA,
  ### order by field \emph{MetadataLink}?
  db = currentDb(),
  ...
  ### additional arguments passed to \code{\link{selectFromTable}}
) 
{
  arguments <- list(
    select = select,
    select_MetadataID = select_MetadataID,
    select_TopicCategory = select_TopicCategory,
    select_Title = select_Title,
    select_Abstract = select_Abstract,
    select_ProfileVersion = select_ProfileVersion,
    select_MetadataLink = select_MetadataLink ,
    where = where,
    where_MetadataID = where_MetadataID,
    where_TopicCategory = where_TopicCategory,
    where_Title = where_Title,
    where_Abstract = where_Abstract,
    where_ProfileVersion = where_ProfileVersion,
    where_MetadataLink = where_MetadataLink ,
    orderBy = orderBy,
    orderBy_MetadataID = orderBy_MetadataID,
    orderBy_TopicCategory = orderBy_TopicCategory,
    orderBy_Title = orderBy_Title,
    orderBy_Abstract = orderBy_Abstract,
    orderBy_ProfileVersion = orderBy_ProfileVersion,
    orderBy_MetadataLink = orderBy_MetadataLink
  )

  selectFromTable(db, 'ISOMetadata', arguments, ...)
}

# odm_LabMethods ---------------------------------------------------------------
odm_LabMethods <- function # select records from LabMethods
### select and filter records from LabMethods
(
  where = NULL,
  ### WHERE condition
  where_LabMethodID = NA,
  ### condition for field \emph{LabMethodID}: Unique integer identifier for each laboratory method. This is the key used by the Samples table to reference a laboratory method.
  where_LabName = NA,
  ### condition for field \emph{LabName}: Name of the laboratory responsible for processing the sample.
  where_LabOrganization = NA,
  ### condition for field \emph{LabOrganization}: Organization responsible for sample analysis.
  where_LabMethodName = NA,
  ### condition for field \emph{LabMethodName}: Name of the method and protocols used for sample analysis.
  where_LabMethodDescription = NA,
  ### condition for field \emph{LabMethodDescription}: Description of the method and protocols used for sample analysis.
  where_LabMethodLink = NA,
  ### condition for field \emph{LabMethodLink}: Link to additional reference material on the analysis method.
  select = NULL,
  ### fields/expressions to select
  select_LabMethodID = NA,
  ### select field \emph{LabMethodID}?
  select_LabName = NA,
  ### select field \emph{LabName}?
  select_LabOrganization = NA,
  ### select field \emph{LabOrganization}?
  select_LabMethodName = NA,
  ### select field \emph{LabMethodName}?
  select_LabMethodDescription = NA,
  ### select field \emph{LabMethodDescription}?
  select_LabMethodLink = NA,
  ### select field \emph{LabMethodLink}?
  orderBy = NULL,
  ### ORDER BY clause of SQL expression
  orderBy_LabMethodID = NA,
  ### order by field \emph{LabMethodID}?
  orderBy_LabName = NA,
  ### order by field \emph{LabName}?
  orderBy_LabOrganization = NA,
  ### order by field \emph{LabOrganization}?
  orderBy_LabMethodName = NA,
  ### order by field \emph{LabMethodName}?
  orderBy_LabMethodDescription = NA,
  ### order by field \emph{LabMethodDescription}?
  orderBy_LabMethodLink = NA,
  ### order by field \emph{LabMethodLink}?
  db = currentDb(),
  ...
  ### additional arguments passed to \code{\link{selectFromTable}}
) 
{
  arguments <- list(
    select = select,
    select_LabMethodID = select_LabMethodID,
    select_LabName = select_LabName,
    select_LabOrganization = select_LabOrganization,
    select_LabMethodName = select_LabMethodName,
    select_LabMethodDescription = select_LabMethodDescription,
    select_LabMethodLink = select_LabMethodLink ,
    where = where,
    where_LabMethodID = where_LabMethodID,
    where_LabName = where_LabName,
    where_LabOrganization = where_LabOrganization,
    where_LabMethodName = where_LabMethodName,
    where_LabMethodDescription = where_LabMethodDescription,
    where_LabMethodLink = where_LabMethodLink ,
    orderBy = orderBy,
    orderBy_LabMethodID = orderBy_LabMethodID,
    orderBy_LabName = orderBy_LabName,
    orderBy_LabOrganization = orderBy_LabOrganization,
    orderBy_LabMethodName = orderBy_LabMethodName,
    orderBy_LabMethodDescription = orderBy_LabMethodDescription,
    orderBy_LabMethodLink = orderBy_LabMethodLink
  )

  selectFromTable(db, 'LabMethods', arguments, ...)
}

# odm_Methods ------------------------------------------------------------------
odm_Methods <- function # select records from Methods
### select and filter records from Methods
(
  where = NULL,
  ### WHERE condition
  where_MethodID = NA,
  ### condition for field \emph{MethodID}: Unique integer ID for each method.
  where_MethodDescription = NA,
  ### condition for field \emph{MethodDescription}: Text description of each method.
  where_MethodLink = NA,
  ### condition for field \emph{MethodLink}: Link to additional reference material on the method.
  select = NULL,
  ### fields/expressions to select
  select_MethodID = NA,
  ### select field \emph{MethodID}?
  select_MethodDescription = NA,
  ### select field \emph{MethodDescription}?
  select_MethodLink = NA,
  ### select field \emph{MethodLink}?
  orderBy = NULL,
  ### ORDER BY clause of SQL expression
  orderBy_MethodID = NA,
  ### order by field \emph{MethodID}?
  orderBy_MethodDescription = NA,
  ### order by field \emph{MethodDescription}?
  orderBy_MethodLink = NA,
  ### order by field \emph{MethodLink}?
  db = currentDb(),
  ...
  ### additional arguments passed to \code{\link{selectFromTable}}
) 
{
  arguments <- list(
    select = select,
    select_MethodID = select_MethodID,
    select_MethodDescription = select_MethodDescription,
    select_MethodLink = select_MethodLink ,
    where = where,
    where_MethodID = where_MethodID,
    where_MethodDescription = where_MethodDescription,
    where_MethodLink = where_MethodLink ,
    orderBy = orderBy,
    orderBy_MethodID = orderBy_MethodID,
    orderBy_MethodDescription = orderBy_MethodDescription,
    orderBy_MethodLink = orderBy_MethodLink
  )

  selectFromTable(db, 'Methods', arguments, ...)
}

# odm_ODMVersion ---------------------------------------------------------------
odm_ODMVersion <- function # select records from ODMVersion
### select and filter records from ODMVersion
(
  where = NULL,
  ### WHERE condition
  where_VersionNumber = NA,
  ### condition for field \emph{VersionNumber}: String that lists the version of the ODM database.
  select = NULL,
  ### fields/expressions to select
  select_VersionNumber = NA,
  ### select field \emph{VersionNumber}?
  orderBy = NULL,
  ### ORDER BY clause of SQL expression
  orderBy_VersionNumber = NA,
  ### order by field \emph{VersionNumber}?
  db = currentDb(),
  ...
  ### additional arguments passed to \code{\link{selectFromTable}}
) 
{
  arguments <- list(
    select = select,
    select_VersionNumber = select_VersionNumber ,
    where = where,
    where_VersionNumber = where_VersionNumber ,
    orderBy = orderBy,
    orderBy_VersionNumber = orderBy_VersionNumber
  )

  selectFromTable(db, 'ODMVersion', arguments, ...)
}

# odm_OffsetTypes --------------------------------------------------------------
odm_OffsetTypes <- function # select records from OffsetTypes
### select and filter records from OffsetTypes
(
  where = NULL,
  ### WHERE condition
  where_OffsetTypeID = NA,
  ### condition for field \emph{OffsetTypeID}: Unique integer identifier that identifies the type of measurement offset.
  where_OffsetUnitsID = NA,
  ### condition for field \emph{OffsetUnitsID}: Integer identifier that references the record in the Units table giving the Units of the OffsetValue.
  where_OffsetDescription = NA,
  ### condition for field \emph{OffsetDescription}: Full text description of the offset type.
  select = NULL,
  ### fields/expressions to select
  select_OffsetTypeID = NA,
  ### select field \emph{OffsetTypeID}?
  select_OffsetUnitsID = NA,
  ### select field \emph{OffsetUnitsID}?
  select_OffsetDescription = NA,
  ### select field \emph{OffsetDescription}?
  orderBy = NULL,
  ### ORDER BY clause of SQL expression
  orderBy_OffsetTypeID = NA,
  ### order by field \emph{OffsetTypeID}?
  orderBy_OffsetUnitsID = NA,
  ### order by field \emph{OffsetUnitsID}?
  orderBy_OffsetDescription = NA,
  ### order by field \emph{OffsetDescription}?
  db = currentDb(),
  ...
  ### additional arguments passed to \code{\link{selectFromTable}}
) 
{
  arguments <- list(
    select = select,
    select_OffsetTypeID = select_OffsetTypeID,
    select_OffsetUnitsID = select_OffsetUnitsID,
    select_OffsetDescription = select_OffsetDescription ,
    where = where,
    where_OffsetTypeID = where_OffsetTypeID,
    where_OffsetUnitsID = where_OffsetUnitsID,
    where_OffsetDescription = where_OffsetDescription ,
    orderBy = orderBy,
    orderBy_OffsetTypeID = orderBy_OffsetTypeID,
    orderBy_OffsetUnitsID = orderBy_OffsetUnitsID,
    orderBy_OffsetDescription = orderBy_OffsetDescription
  )

  selectFromTable(db, 'OffsetTypes', arguments, ...)
}

# odm_Qualifiers ---------------------------------------------------------------
odm_Qualifiers <- function # select records from Qualifiers
### select and filter records from Qualifiers
(
  where = NULL,
  ### WHERE condition
  where_QualifierID = NA,
  ### condition for field \emph{QualifierID}: Unique integer identifying the data qualifier.
  where_QualifierCode = NA,
  ### condition for field \emph{QualifierCode}: Text code used by organization that collects the data.
  where_QualifierDescription = NA,
  ### condition for field \emph{QualifierDescription}: Text of the data qualifying comment.
  select = NULL,
  ### fields/expressions to select
  select_QualifierID = NA,
  ### select field \emph{QualifierID}?
  select_QualifierCode = NA,
  ### select field \emph{QualifierCode}?
  select_QualifierDescription = NA,
  ### select field \emph{QualifierDescription}?
  orderBy = NULL,
  ### ORDER BY clause of SQL expression
  orderBy_QualifierID = NA,
  ### order by field \emph{QualifierID}?
  orderBy_QualifierCode = NA,
  ### order by field \emph{QualifierCode}?
  orderBy_QualifierDescription = NA,
  ### order by field \emph{QualifierDescription}?
  db = currentDb(),
  ...
  ### additional arguments passed to \code{\link{selectFromTable}}
) 
{
  arguments <- list(
    select = select,
    select_QualifierID = select_QualifierID,
    select_QualifierCode = select_QualifierCode,
    select_QualifierDescription = select_QualifierDescription ,
    where = where,
    where_QualifierID = where_QualifierID,
    where_QualifierCode = where_QualifierCode,
    where_QualifierDescription = where_QualifierDescription ,
    orderBy = orderBy,
    orderBy_QualifierID = orderBy_QualifierID,
    orderBy_QualifierCode = orderBy_QualifierCode,
    orderBy_QualifierDescription = orderBy_QualifierDescription
  )

  selectFromTable(db, 'Qualifiers', arguments, ...)
}

# odm_QualityControlLevels -----------------------------------------------------
odm_QualityControlLevels <- function # select records from QualityControlLevels
### select and filter records from QualityControlLevels
(
  where = NULL,
  ### WHERE condition
  where_QualityControlLevelID = NA,
  ### condition for field \emph{QualityControlLevelID}: Unique integer identifying the quality control level.
  where_QualityControlLevelCode = NA,
  ### condition for field \emph{QualityControlLevelCode}: Code used to identify the level of quality control to which data values have been subjected.
  where_Definition = NA,
  ### condition for field \emph{Definition}: Definition of Quality Control Level.
  where_Explanation = NA,
  ### condition for field \emph{Explanation}: Explanation of Quality Control Level
  select = NULL,
  ### fields/expressions to select
  select_QualityControlLevelID = NA,
  ### select field \emph{QualityControlLevelID}?
  select_QualityControlLevelCode = NA,
  ### select field \emph{QualityControlLevelCode}?
  select_Definition = NA,
  ### select field \emph{Definition}?
  select_Explanation = NA,
  ### select field \emph{Explanation}?
  orderBy = NULL,
  ### ORDER BY clause of SQL expression
  orderBy_QualityControlLevelID = NA,
  ### order by field \emph{QualityControlLevelID}?
  orderBy_QualityControlLevelCode = NA,
  ### order by field \emph{QualityControlLevelCode}?
  orderBy_Definition = NA,
  ### order by field \emph{Definition}?
  orderBy_Explanation = NA,
  ### order by field \emph{Explanation}?
  db = currentDb(),
  ...
  ### additional arguments passed to \code{\link{selectFromTable}}
) 
{
  arguments <- list(
    select = select,
    select_QualityControlLevelID = select_QualityControlLevelID,
    select_QualityControlLevelCode = select_QualityControlLevelCode,
    select_Definition = select_Definition,
    select_Explanation = select_Explanation ,
    where = where,
    where_QualityControlLevelID = where_QualityControlLevelID,
    where_QualityControlLevelCode = where_QualityControlLevelCode,
    where_Definition = where_Definition,
    where_Explanation = where_Explanation ,
    orderBy = orderBy,
    orderBy_QualityControlLevelID = orderBy_QualityControlLevelID,
    orderBy_QualityControlLevelCode = orderBy_QualityControlLevelCode,
    orderBy_Definition = orderBy_Definition,
    orderBy_Explanation = orderBy_Explanation
  )

  selectFromTable(db, 'QualityControlLevels', arguments, ...)
}

# odm_SampleMediumCV -----------------------------------------------------------
odm_SampleMediumCV <- function # select records from SampleMediumCV
### select and filter records from SampleMediumCV
(
  where = NULL,
  ### WHERE condition
  where_Term = NA,
  ### condition for field \emph{Term}: Controlled vocabulary forsample media.
  where_Definition = NA,
  ### condition for field \emph{Definition}: Definition of sample mediacontrolled vocabulary term. Thedefinition is optional if the termis self explanatory.
  select = NULL,
  ### fields/expressions to select
  select_Term = NA,
  ### select field \emph{Term}?
  select_Definition = NA,
  ### select field \emph{Definition}?
  orderBy = NULL,
  ### ORDER BY clause of SQL expression
  orderBy_Term = NA,
  ### order by field \emph{Term}?
  orderBy_Definition = NA,
  ### order by field \emph{Definition}?
  db = currentDb(),
  ...
  ### additional arguments passed to \code{\link{selectFromTable}}
) 
{
  arguments <- list(
    select = select,
    select_Term = select_Term,
    select_Definition = select_Definition ,
    where = where,
    where_Term = where_Term,
    where_Definition = where_Definition ,
    orderBy = orderBy,
    orderBy_Term = orderBy_Term,
    orderBy_Definition = orderBy_Definition
  )

  selectFromTable(db, 'SampleMediumCV', arguments, ...)
}

# odm_Samples ------------------------------------------------------------------
odm_Samples <- function # select records from Samples
### select and filter records from Samples
(
  where = NULL,
  ### WHERE condition
  where_SampleID = NA,
  ### condition for field \emph{SampleID}: Unique integer identifier that identifies each physical sample.
  where_SampleType = NA,
  ### condition for field \emph{SampleType}: Controlled vocabulary specifying the sample type from the SampleTypeCV table.
  where_LabSampleCode = NA,
  ### condition for field \emph{LabSampleCode}: Code or label used to identify and track lab sample or sample container (e.g. bottle) during lab analysis.
  where_LabMethodID = NA,
  ### condition for field \emph{LabMethodID}: Unique identifier for the laboratory method used to process the sample. This references the LabMethods table.
  select = NULL,
  ### fields/expressions to select
  select_SampleID = NA,
  ### select field \emph{SampleID}?
  select_SampleType = NA,
  ### select field \emph{SampleType}?
  select_LabSampleCode = NA,
  ### select field \emph{LabSampleCode}?
  select_LabMethodID = NA,
  ### select field \emph{LabMethodID}?
  orderBy = NULL,
  ### ORDER BY clause of SQL expression
  orderBy_SampleID = NA,
  ### order by field \emph{SampleID}?
  orderBy_SampleType = NA,
  ### order by field \emph{SampleType}?
  orderBy_LabSampleCode = NA,
  ### order by field \emph{LabSampleCode}?
  orderBy_LabMethodID = NA,
  ### order by field \emph{LabMethodID}?
  db = currentDb(),
  ...
  ### additional arguments passed to \code{\link{selectFromTable}}
) 
{
  arguments <- list(
    select = select,
    select_SampleID = select_SampleID,
    select_SampleType = select_SampleType,
    select_LabSampleCode = select_LabSampleCode,
    select_LabMethodID = select_LabMethodID ,
    where = where,
    where_SampleID = where_SampleID,
    where_SampleType = where_SampleType,
    where_LabSampleCode = where_LabSampleCode,
    where_LabMethodID = where_LabMethodID ,
    orderBy = orderBy,
    orderBy_SampleID = orderBy_SampleID,
    orderBy_SampleType = orderBy_SampleType,
    orderBy_LabSampleCode = orderBy_LabSampleCode,
    orderBy_LabMethodID = orderBy_LabMethodID
  )

  selectFromTable(db, 'Samples', arguments, ...)
}

# odm_SampleTypeCV -------------------------------------------------------------
odm_SampleTypeCV <- function # select records from SampleTypeCV
### select and filter records from SampleTypeCV
(
  where = NULL,
  ### WHERE condition
  where_Term = NA,
  ### condition for field \emph{Term}: Controlled vocabulary for sample type.
  where_Definition = NA,
  ### condition for field \emph{Definition}: Definition of sample type controlled vocabulary term. The definition is optional if the term is self explanatory.
  select = NULL,
  ### fields/expressions to select
  select_Term = NA,
  ### select field \emph{Term}?
  select_Definition = NA,
  ### select field \emph{Definition}?
  orderBy = NULL,
  ### ORDER BY clause of SQL expression
  orderBy_Term = NA,
  ### order by field \emph{Term}?
  orderBy_Definition = NA,
  ### order by field \emph{Definition}?
  db = currentDb(),
  ...
  ### additional arguments passed to \code{\link{selectFromTable}}
) 
{
  arguments <- list(
    select = select,
    select_Term = select_Term,
    select_Definition = select_Definition ,
    where = where,
    where_Term = where_Term,
    where_Definition = where_Definition ,
    orderBy = orderBy,
    orderBy_Term = orderBy_Term,
    orderBy_Definition = orderBy_Definition
  )

  selectFromTable(db, 'SampleTypeCV', arguments, ...)
}

# odm_SeriesCatalog ------------------------------------------------------------
odm_SeriesCatalog <- function # select records from SeriesCatalog
### select and filter records from SeriesCatalog
(
  where = NULL,
  ### WHERE condition
  where_SeriesID = NA,
  ### condition for field \emph{SeriesID}: Unique integer identifier for each data series.
  where_SiteID = NA,
  ### condition for field \emph{SiteID}: Site identifier from the Sites table.
  where_SiteCode = NA,
  ### condition for field \emph{SiteCode}: Site code used by organization that collects the data.
  where_SiteName = NA,
  ### condition for field \emph{SiteName}: Full text name of sampling site.
  where_VariableID = NA,
  ### condition for field \emph{VariableID}: Integer identifier for each Variable that references the Variables table.
  where_VariableCode = NA,
  ### condition for field \emph{VariableCode}: Variable code used by the organization that collects the data.
  where_VariableName = NA,
  ### condition for field \emph{VariableName}: Name of the variable from the variables table.
  where_Speciation = NA,
  ### condition for field \emph{Speciation}: Code used to identify how the data value is expressed (i.e., total phosphorus concentration expressed as P). This should be from the SpeciationCV controlled vocabulary table.
  where_VariableUnitsID = NA,
  ### condition for field \emph{VariableUnitsID}: Integer identifier that references the record in the Units table giving the Units of the data value.
  where_VariableUnitsName = NA,
  ### condition for field \emph{VariableUnitsName}: Full text name of the variable units from the UnitsName field in the Units table.
  where_SampleMedium = NA,
  ### condition for field \emph{SampleMedium}: The medium of the sample. This should be from the SampleMediumCV controlled vocabulary table.
  where_ValueType = NA,
  ### condition for field \emph{ValueType}: Text value indicating what type of data value is being recorded. This should be from the ValueTypeCV controlled vocabulary table.
  where_TimeSupport = NA,
  ### condition for field \emph{TimeSupport}: Numerical value that indicates the time support (or temporal footprint) of the data values. 0 is used to indicate data values that are instantaneous. Other values indicate the time over which the data values are implicitly or explicitly averaged or aggregated.
  where_TimeUnitsID = NA,
  ### condition for field \emph{TimeUnitsID}: Integer identifier that  references the record in the Units table giving the Units of the time support. If TimeSupport is 0, indicating an instantaneous observation, a unit needs to still be given for completeness, although it is somewhat arbitrary.
  where_TimeUnitsName = NA,
  ### condition for field \emph{TimeUnitsName}: Full text name of the time support units from the UnitsName field in the Units table.
  where_DataType = NA,
  ### condition for field \emph{DataType}: Text value that identifies the data as one of several types from the DataTypeCV controlled vocabulary table.
  where_GeneralCategory = NA,
  ### condition for field \emph{GeneralCategory}: General category of the variable from the GeneralCategoryCV table.
  where_MethodID = NA,
  ### condition for field \emph{MethodID}: Integer identifier that identifies the method used to generate the data values and references the Methods table.
  where_MethodDescription = NA,
  ### condition for field \emph{MethodDescription}: Full text description of the method used to generate the data values.
  where_SourceID = NA,
  ### condition for field \emph{SourceID}: Integer identifier that identifies the source of the data values and references the Sources table.
  where_Organization = NA,
  ### condition for field \emph{Organization}: Text description of the source organization from the Sources table.
  where_SourceDescription = NA,
  ### condition for field \emph{SourceDescription}: Text description of the data source from the Sources table.
  where_Citation = NA,
  ### condition for field \emph{Citation}: Text string that give the citation to be used when the data from each source are referenced.
  where_QualityControlLevelID = NA,
  ### condition for field \emph{QualityControlLevelID}: Integer identifier that indicates the level of quality control that the data values have been subjected to.
  where_QualityControlLevelCode = NA,
  ### condition for field \emph{QualityControlLevelCode}: Code used to identify the level of quality control to which data values have been subjected.
  where_BeginDateTime = NA,
  ### condition for field \emph{BeginDateTime}: Date of the first data value in the series. To be programmatically updated if new records are added.
  where_EndDateTime = NA,
  ### condition for field \emph{EndDateTime}: Date of the last data value in the series. To be programmatically updated if new records are added.
  where_BeginDateTimeUTC = NA,
  ### condition for field \emph{BeginDateTimeUTC}: Date of the first data value in the series in UTC. To be programmatically updated if new records are added.
  where_EndDateTimeUTC = NA,
  ### condition for field \emph{EndDateTimeUTC}: Date of the last data value in the series in UTC. To be programmatically updated if new records are added.
  where_ValueCount = NA,
  ### condition for field \emph{ValueCount}: The number of data values in the series identified by the combination of the SiteID, VariableID, MethodID, SourceID and QualityControlLevelID fields. To be programmatically updated if new records are added.
  select = NULL,
  ### fields/expressions to select
  select_SeriesID = NA,
  ### select field \emph{SeriesID}?
  select_SiteID = NA,
  ### select field \emph{SiteID}?
  select_SiteCode = NA,
  ### select field \emph{SiteCode}?
  select_SiteName = NA,
  ### select field \emph{SiteName}?
  select_VariableID = NA,
  ### select field \emph{VariableID}?
  select_VariableCode = NA,
  ### select field \emph{VariableCode}?
  select_VariableName = NA,
  ### select field \emph{VariableName}?
  select_Speciation = NA,
  ### select field \emph{Speciation}?
  select_VariableUnitsID = NA,
  ### select field \emph{VariableUnitsID}?
  select_VariableUnitsName = NA,
  ### select field \emph{VariableUnitsName}?
  select_SampleMedium = NA,
  ### select field \emph{SampleMedium}?
  select_ValueType = NA,
  ### select field \emph{ValueType}?
  select_TimeSupport = NA,
  ### select field \emph{TimeSupport}?
  select_TimeUnitsID = NA,
  ### select field \emph{TimeUnitsID}?
  select_TimeUnitsName = NA,
  ### select field \emph{TimeUnitsName}?
  select_DataType = NA,
  ### select field \emph{DataType}?
  select_GeneralCategory = NA,
  ### select field \emph{GeneralCategory}?
  select_MethodID = NA,
  ### select field \emph{MethodID}?
  select_MethodDescription = NA,
  ### select field \emph{MethodDescription}?
  select_SourceID = NA,
  ### select field \emph{SourceID}?
  select_Organization = NA,
  ### select field \emph{Organization}?
  select_SourceDescription = NA,
  ### select field \emph{SourceDescription}?
  select_Citation = NA,
  ### select field \emph{Citation}?
  select_QualityControlLevelID = NA,
  ### select field \emph{QualityControlLevelID}?
  select_QualityControlLevelCode = NA,
  ### select field \emph{QualityControlLevelCode}?
  select_BeginDateTime = NA,
  ### select field \emph{BeginDateTime}?
  select_EndDateTime = NA,
  ### select field \emph{EndDateTime}?
  select_BeginDateTimeUTC = NA,
  ### select field \emph{BeginDateTimeUTC}?
  select_EndDateTimeUTC = NA,
  ### select field \emph{EndDateTimeUTC}?
  select_ValueCount = NA,
  ### select field \emph{ValueCount}?
  orderBy = NULL,
  ### ORDER BY clause of SQL expression
  orderBy_SeriesID = NA,
  ### order by field \emph{SeriesID}?
  orderBy_SiteID = NA,
  ### order by field \emph{SiteID}?
  orderBy_SiteCode = NA,
  ### order by field \emph{SiteCode}?
  orderBy_SiteName = NA,
  ### order by field \emph{SiteName}?
  orderBy_VariableID = NA,
  ### order by field \emph{VariableID}?
  orderBy_VariableCode = NA,
  ### order by field \emph{VariableCode}?
  orderBy_VariableName = NA,
  ### order by field \emph{VariableName}?
  orderBy_Speciation = NA,
  ### order by field \emph{Speciation}?
  orderBy_VariableUnitsID = NA,
  ### order by field \emph{VariableUnitsID}?
  orderBy_VariableUnitsName = NA,
  ### order by field \emph{VariableUnitsName}?
  orderBy_SampleMedium = NA,
  ### order by field \emph{SampleMedium}?
  orderBy_ValueType = NA,
  ### order by field \emph{ValueType}?
  orderBy_TimeSupport = NA,
  ### order by field \emph{TimeSupport}?
  orderBy_TimeUnitsID = NA,
  ### order by field \emph{TimeUnitsID}?
  orderBy_TimeUnitsName = NA,
  ### order by field \emph{TimeUnitsName}?
  orderBy_DataType = NA,
  ### order by field \emph{DataType}?
  orderBy_GeneralCategory = NA,
  ### order by field \emph{GeneralCategory}?
  orderBy_MethodID = NA,
  ### order by field \emph{MethodID}?
  orderBy_MethodDescription = NA,
  ### order by field \emph{MethodDescription}?
  orderBy_SourceID = NA,
  ### order by field \emph{SourceID}?
  orderBy_Organization = NA,
  ### order by field \emph{Organization}?
  orderBy_SourceDescription = NA,
  ### order by field \emph{SourceDescription}?
  orderBy_Citation = NA,
  ### order by field \emph{Citation}?
  orderBy_QualityControlLevelID = NA,
  ### order by field \emph{QualityControlLevelID}?
  orderBy_QualityControlLevelCode = NA,
  ### order by field \emph{QualityControlLevelCode}?
  orderBy_BeginDateTime = NA,
  ### order by field \emph{BeginDateTime}?
  orderBy_EndDateTime = NA,
  ### order by field \emph{EndDateTime}?
  orderBy_BeginDateTimeUTC = NA,
  ### order by field \emph{BeginDateTimeUTC}?
  orderBy_EndDateTimeUTC = NA,
  ### order by field \emph{EndDateTimeUTC}?
  orderBy_ValueCount = NA,
  ### order by field \emph{ValueCount}?
  db = currentDb(),
  ...
  ### additional arguments passed to \code{\link{selectFromTable}}
) 
{
  arguments <- list(
    select = select,
    select_SeriesID = select_SeriesID,
    select_SiteID = select_SiteID,
    select_SiteCode = select_SiteCode,
    select_SiteName = select_SiteName,
    select_VariableID = select_VariableID,
    select_VariableCode = select_VariableCode,
    select_VariableName = select_VariableName,
    select_Speciation = select_Speciation,
    select_VariableUnitsID = select_VariableUnitsID,
    select_VariableUnitsName = select_VariableUnitsName,
    select_SampleMedium = select_SampleMedium,
    select_ValueType = select_ValueType,
    select_TimeSupport = select_TimeSupport,
    select_TimeUnitsID = select_TimeUnitsID,
    select_TimeUnitsName = select_TimeUnitsName,
    select_DataType = select_DataType,
    select_GeneralCategory = select_GeneralCategory,
    select_MethodID = select_MethodID,
    select_MethodDescription = select_MethodDescription,
    select_SourceID = select_SourceID,
    select_Organization = select_Organization,
    select_SourceDescription = select_SourceDescription,
    select_Citation = select_Citation,
    select_QualityControlLevelID = select_QualityControlLevelID,
    select_QualityControlLevelCode = select_QualityControlLevelCode,
    select_BeginDateTime = select_BeginDateTime,
    select_EndDateTime = select_EndDateTime,
    select_BeginDateTimeUTC = select_BeginDateTimeUTC,
    select_EndDateTimeUTC = select_EndDateTimeUTC,
    select_ValueCount = select_ValueCount ,
    where = where,
    where_SeriesID = where_SeriesID,
    where_SiteID = where_SiteID,
    where_SiteCode = where_SiteCode,
    where_SiteName = where_SiteName,
    where_VariableID = where_VariableID,
    where_VariableCode = where_VariableCode,
    where_VariableName = where_VariableName,
    where_Speciation = where_Speciation,
    where_VariableUnitsID = where_VariableUnitsID,
    where_VariableUnitsName = where_VariableUnitsName,
    where_SampleMedium = where_SampleMedium,
    where_ValueType = where_ValueType,
    where_TimeSupport = where_TimeSupport,
    where_TimeUnitsID = where_TimeUnitsID,
    where_TimeUnitsName = where_TimeUnitsName,
    where_DataType = where_DataType,
    where_GeneralCategory = where_GeneralCategory,
    where_MethodID = where_MethodID,
    where_MethodDescription = where_MethodDescription,
    where_SourceID = where_SourceID,
    where_Organization = where_Organization,
    where_SourceDescription = where_SourceDescription,
    where_Citation = where_Citation,
    where_QualityControlLevelID = where_QualityControlLevelID,
    where_QualityControlLevelCode = where_QualityControlLevelCode,
    where_BeginDateTime = where_BeginDateTime,
    where_EndDateTime = where_EndDateTime,
    where_BeginDateTimeUTC = where_BeginDateTimeUTC,
    where_EndDateTimeUTC = where_EndDateTimeUTC,
    where_ValueCount = where_ValueCount ,
    orderBy = orderBy,
    orderBy_SeriesID = orderBy_SeriesID,
    orderBy_SiteID = orderBy_SiteID,
    orderBy_SiteCode = orderBy_SiteCode,
    orderBy_SiteName = orderBy_SiteName,
    orderBy_VariableID = orderBy_VariableID,
    orderBy_VariableCode = orderBy_VariableCode,
    orderBy_VariableName = orderBy_VariableName,
    orderBy_Speciation = orderBy_Speciation,
    orderBy_VariableUnitsID = orderBy_VariableUnitsID,
    orderBy_VariableUnitsName = orderBy_VariableUnitsName,
    orderBy_SampleMedium = orderBy_SampleMedium,
    orderBy_ValueType = orderBy_ValueType,
    orderBy_TimeSupport = orderBy_TimeSupport,
    orderBy_TimeUnitsID = orderBy_TimeUnitsID,
    orderBy_TimeUnitsName = orderBy_TimeUnitsName,
    orderBy_DataType = orderBy_DataType,
    orderBy_GeneralCategory = orderBy_GeneralCategory,
    orderBy_MethodID = orderBy_MethodID,
    orderBy_MethodDescription = orderBy_MethodDescription,
    orderBy_SourceID = orderBy_SourceID,
    orderBy_Organization = orderBy_Organization,
    orderBy_SourceDescription = orderBy_SourceDescription,
    orderBy_Citation = orderBy_Citation,
    orderBy_QualityControlLevelID = orderBy_QualityControlLevelID,
    orderBy_QualityControlLevelCode = orderBy_QualityControlLevelCode,
    orderBy_BeginDateTime = orderBy_BeginDateTime,
    orderBy_EndDateTime = orderBy_EndDateTime,
    orderBy_BeginDateTimeUTC = orderBy_BeginDateTimeUTC,
    orderBy_EndDateTimeUTC = orderBy_EndDateTimeUTC,
    orderBy_ValueCount = orderBy_ValueCount
  )

  selectFromTable(db, 'SeriesCatalog', arguments, ...)
}

# odm_Sites --------------------------------------------------------------------
odm_Sites <- function # select records from Sites
### select and filter records from Sites
(
  where = NULL,
  ### WHERE condition
  where_SiteID = NA,
  ### condition for field \emph{SiteID}: Unique identifier for each sampling location.
  where_SiteCode = NA,
  ### condition for field \emph{SiteCode}: Code used by organization that collects the data to identify the site
  where_SiteName = NA,
  ### condition for field \emph{SiteName}: SiteName
  where_Latitude = NA,
  ### condition for field \emph{Latitude}: Latitude in decimal degrees.
  where_Longitude = NA,
  ### condition for field \emph{Longitude}: Longitude in decimal degrees. East positive, West negative.
  where_LatLongDatumID = NA,
  ### condition for field \emph{LatLongDatumID}: Identifier that references the Spatial Reference System of the latitude and longitude coordinates in the SpatialReferences table.
  where_Elevation_m = NA,
  ### condition for field \emph{Elevation_m}: Elevation of sampling location (in m). If this is not provided it needs to be obtained programmatically from a DEM based on location information.
  where_VerticalDatum = NA,
  ### condition for field \emph{VerticalDatum}: Vertical datum of the elevation. Controlled Vocabulary from VerticalDatumCV.
  where_LocalX = NA,
  ### condition for field \emph{LocalX}: Local Projection X coordinate.
  where_LocalY = NA,
  ### condition for field \emph{LocalY}: Local Projection Y Coordinate.
  where_LocalProjectionID = NA,
  ### condition for field \emph{LocalProjectionID}: Identifier that references the Spatial Reference System of the local coordinates in the SpatialReferences table. This field is required if local coordinates are given.
  where_PosAccuracy_m = NA,
  ### condition for field \emph{PosAccuracy_m}: Value giving the accuracy with which the positional information is specified in meters.
  where_State = NA,
  ### condition for field \emph{State}: Name of state in which the monitoring site is located.
  where_County = NA,
  ### condition for field \emph{County}: Name of county in which the monitoring site is located.
  where_Comments = NA,
  ### condition for field \emph{Comments}: Comments related to the site.
  select = NULL,
  ### fields/expressions to select
  select_SiteID = NA,
  ### select field \emph{SiteID}?
  select_SiteCode = NA,
  ### select field \emph{SiteCode}?
  select_SiteName = NA,
  ### select field \emph{SiteName}?
  select_Latitude = NA,
  ### select field \emph{Latitude}?
  select_Longitude = NA,
  ### select field \emph{Longitude}?
  select_LatLongDatumID = NA,
  ### select field \emph{LatLongDatumID}?
  select_Elevation_m = NA,
  ### select field \emph{Elevation_m}?
  select_VerticalDatum = NA,
  ### select field \emph{VerticalDatum}?
  select_LocalX = NA,
  ### select field \emph{LocalX}?
  select_LocalY = NA,
  ### select field \emph{LocalY}?
  select_LocalProjectionID = NA,
  ### select field \emph{LocalProjectionID}?
  select_PosAccuracy_m = NA,
  ### select field \emph{PosAccuracy_m}?
  select_State = NA,
  ### select field \emph{State}?
  select_County = NA,
  ### select field \emph{County}?
  select_Comments = NA,
  ### select field \emph{Comments}?
  orderBy = NULL,
  ### ORDER BY clause of SQL expression
  orderBy_SiteID = NA,
  ### order by field \emph{SiteID}?
  orderBy_SiteCode = NA,
  ### order by field \emph{SiteCode}?
  orderBy_SiteName = NA,
  ### order by field \emph{SiteName}?
  orderBy_Latitude = NA,
  ### order by field \emph{Latitude}?
  orderBy_Longitude = NA,
  ### order by field \emph{Longitude}?
  orderBy_LatLongDatumID = NA,
  ### order by field \emph{LatLongDatumID}?
  orderBy_Elevation_m = NA,
  ### order by field \emph{Elevation_m}?
  orderBy_VerticalDatum = NA,
  ### order by field \emph{VerticalDatum}?
  orderBy_LocalX = NA,
  ### order by field \emph{LocalX}?
  orderBy_LocalY = NA,
  ### order by field \emph{LocalY}?
  orderBy_LocalProjectionID = NA,
  ### order by field \emph{LocalProjectionID}?
  orderBy_PosAccuracy_m = NA,
  ### order by field \emph{PosAccuracy_m}?
  orderBy_State = NA,
  ### order by field \emph{State}?
  orderBy_County = NA,
  ### order by field \emph{County}?
  orderBy_Comments = NA,
  ### order by field \emph{Comments}?
  db = currentDb(),
  ...
  ### additional arguments passed to \code{\link{selectFromTable}}
) 
{
  arguments <- list(
    select = select,
    select_SiteID = select_SiteID,
    select_SiteCode = select_SiteCode,
    select_SiteName = select_SiteName,
    select_Latitude = select_Latitude,
    select_Longitude = select_Longitude,
    select_LatLongDatumID = select_LatLongDatumID,
    select_Elevation_m = select_Elevation_m,
    select_VerticalDatum = select_VerticalDatum,
    select_LocalX = select_LocalX,
    select_LocalY = select_LocalY,
    select_LocalProjectionID = select_LocalProjectionID,
    select_PosAccuracy_m = select_PosAccuracy_m,
    select_State = select_State,
    select_County = select_County,
    select_Comments = select_Comments ,
    where = where,
    where_SiteID = where_SiteID,
    where_SiteCode = where_SiteCode,
    where_SiteName = where_SiteName,
    where_Latitude = where_Latitude,
    where_Longitude = where_Longitude,
    where_LatLongDatumID = where_LatLongDatumID,
    where_Elevation_m = where_Elevation_m,
    where_VerticalDatum = where_VerticalDatum,
    where_LocalX = where_LocalX,
    where_LocalY = where_LocalY,
    where_LocalProjectionID = where_LocalProjectionID,
    where_PosAccuracy_m = where_PosAccuracy_m,
    where_State = where_State,
    where_County = where_County,
    where_Comments = where_Comments ,
    orderBy = orderBy,
    orderBy_SiteID = orderBy_SiteID,
    orderBy_SiteCode = orderBy_SiteCode,
    orderBy_SiteName = orderBy_SiteName,
    orderBy_Latitude = orderBy_Latitude,
    orderBy_Longitude = orderBy_Longitude,
    orderBy_LatLongDatumID = orderBy_LatLongDatumID,
    orderBy_Elevation_m = orderBy_Elevation_m,
    orderBy_VerticalDatum = orderBy_VerticalDatum,
    orderBy_LocalX = orderBy_LocalX,
    orderBy_LocalY = orderBy_LocalY,
    orderBy_LocalProjectionID = orderBy_LocalProjectionID,
    orderBy_PosAccuracy_m = orderBy_PosAccuracy_m,
    orderBy_State = orderBy_State,
    orderBy_County = orderBy_County,
    orderBy_Comments = orderBy_Comments
  )

  selectFromTable(db, 'Sites', arguments, ...)
}

# odm_Sources ------------------------------------------------------------------
odm_Sources <- function # select records from Sources
### select and filter records from Sources
(
  where = NULL,
  ### WHERE condition
  where_SourceID = NA,
  ### condition for field \emph{SourceID}: Unique integer identifier that identifies each data source.
  where_Organization = NA,
  ### condition for field \emph{Organization}: Name of the organization that collected the data. This should be the agency or organization that collected the data, even if it came out of a database consolidated from many sources such as STORET.
  where_SourceDescription = NA,
  ### condition for field \emph{SourceDescription}: Full text description of the source of the data.
  where_SourceLink = NA,
  ### condition for field \emph{SourceLink}: Link that can be pointed at the original data file and/or associated metadata stored in the digital library or URL of data source.
  where_ContactName = NA,
  ### condition for field \emph{ContactName}: Name of the contact person for the data source.
  where_Phone = NA,
  ### condition for field \emph{Phone}: Phone number for the contact person.
  where_Email = NA,
  ### condition for field \emph{Email}: Email address for the contact person.
  where_Address = NA,
  ### condition for field \emph{Address}: Street address for the contact person.
  where_City = NA,
  ### condition for field \emph{City}: City in which the contact person is located.
  where_State = NA,
  ### condition for field \emph{State}: State in which the contact person is located. Use two letter abbreviations for US. For other countries give the full country name.
  where_ZipCode = NA,
  ### condition for field \emph{ZipCode}: US Zip Code or country postal code.
  where_Citation = NA,
  ### condition for field \emph{Citation}: Text string that give the citation to be used when the data from each source are referenced.
  where_MetadataID = NA,
  ### condition for field \emph{MetadataID}: Integer identifier referencing the record in the ISOMetadata table for this source.
  select = NULL,
  ### fields/expressions to select
  select_SourceID = NA,
  ### select field \emph{SourceID}?
  select_Organization = NA,
  ### select field \emph{Organization}?
  select_SourceDescription = NA,
  ### select field \emph{SourceDescription}?
  select_SourceLink = NA,
  ### select field \emph{SourceLink}?
  select_ContactName = NA,
  ### select field \emph{ContactName}?
  select_Phone = NA,
  ### select field \emph{Phone}?
  select_Email = NA,
  ### select field \emph{Email}?
  select_Address = NA,
  ### select field \emph{Address}?
  select_City = NA,
  ### select field \emph{City}?
  select_State = NA,
  ### select field \emph{State}?
  select_ZipCode = NA,
  ### select field \emph{ZipCode}?
  select_Citation = NA,
  ### select field \emph{Citation}?
  select_MetadataID = NA,
  ### select field \emph{MetadataID}?
  orderBy = NULL,
  ### ORDER BY clause of SQL expression
  orderBy_SourceID = NA,
  ### order by field \emph{SourceID}?
  orderBy_Organization = NA,
  ### order by field \emph{Organization}?
  orderBy_SourceDescription = NA,
  ### order by field \emph{SourceDescription}?
  orderBy_SourceLink = NA,
  ### order by field \emph{SourceLink}?
  orderBy_ContactName = NA,
  ### order by field \emph{ContactName}?
  orderBy_Phone = NA,
  ### order by field \emph{Phone}?
  orderBy_Email = NA,
  ### order by field \emph{Email}?
  orderBy_Address = NA,
  ### order by field \emph{Address}?
  orderBy_City = NA,
  ### order by field \emph{City}?
  orderBy_State = NA,
  ### order by field \emph{State}?
  orderBy_ZipCode = NA,
  ### order by field \emph{ZipCode}?
  orderBy_Citation = NA,
  ### order by field \emph{Citation}?
  orderBy_MetadataID = NA,
  ### order by field \emph{MetadataID}?
  db = currentDb(),
  ...
  ### additional arguments passed to \code{\link{selectFromTable}}
) 
{
  arguments <- list(
    select = select,
    select_SourceID = select_SourceID,
    select_Organization = select_Organization,
    select_SourceDescription = select_SourceDescription,
    select_SourceLink = select_SourceLink,
    select_ContactName = select_ContactName,
    select_Phone = select_Phone,
    select_Email = select_Email,
    select_Address = select_Address,
    select_City = select_City,
    select_State = select_State,
    select_ZipCode = select_ZipCode,
    select_Citation = select_Citation,
    select_MetadataID = select_MetadataID ,
    where = where,
    where_SourceID = where_SourceID,
    where_Organization = where_Organization,
    where_SourceDescription = where_SourceDescription,
    where_SourceLink = where_SourceLink,
    where_ContactName = where_ContactName,
    where_Phone = where_Phone,
    where_Email = where_Email,
    where_Address = where_Address,
    where_City = where_City,
    where_State = where_State,
    where_ZipCode = where_ZipCode,
    where_Citation = where_Citation,
    where_MetadataID = where_MetadataID ,
    orderBy = orderBy,
    orderBy_SourceID = orderBy_SourceID,
    orderBy_Organization = orderBy_Organization,
    orderBy_SourceDescription = orderBy_SourceDescription,
    orderBy_SourceLink = orderBy_SourceLink,
    orderBy_ContactName = orderBy_ContactName,
    orderBy_Phone = orderBy_Phone,
    orderBy_Email = orderBy_Email,
    orderBy_Address = orderBy_Address,
    orderBy_City = orderBy_City,
    orderBy_State = orderBy_State,
    orderBy_ZipCode = orderBy_ZipCode,
    orderBy_Citation = orderBy_Citation,
    orderBy_MetadataID = orderBy_MetadataID
  )

  selectFromTable(db, 'Sources', arguments, ...)
}

# odm_SpatialReferences --------------------------------------------------------
odm_SpatialReferences <- function # select records from SpatialReferences
### select and filter records from SpatialReferences
(
  where = NULL,
  ### WHERE condition
  where_SpatialReferenceID = NA,
  ### condition for field \emph{SpatialReferenceID}: Unique integer identifier for each Spatial Reference System.
  where_SRSID = NA,
  ### condition for field \emph{SRSID}: Integer identifier for the Spatial Reference System from http://www.epsg.org/.
  where_SRSName = NA,
  ### condition for field \emph{SRSName}: Name of the Spatial Reference System.
  where_IsGeographic = NA,
  ### condition for field \emph{IsGeographic}: Value that indicates whether the spatial reference system uses geographic coordinates (i.e. latitude and longitude) or not.
  where_Notes = NA,
  ### condition for field \emph{Notes}: Descriptive information about the Spatial Reference System. This field would be used to define a non-standard study area specific system if necessary and would contain a description of the local projection information. Where possible, this should refer to a standard projection, in which case latitude and longitude can be determined from local projection  information. If the local grid system is non-standard then latitude and longitude need to be included too.
  select = NULL,
  ### fields/expressions to select
  select_SpatialReferenceID = NA,
  ### select field \emph{SpatialReferenceID}?
  select_SRSID = NA,
  ### select field \emph{SRSID}?
  select_SRSName = NA,
  ### select field \emph{SRSName}?
  select_IsGeographic = NA,
  ### select field \emph{IsGeographic}?
  select_Notes = NA,
  ### select field \emph{Notes}?
  orderBy = NULL,
  ### ORDER BY clause of SQL expression
  orderBy_SpatialReferenceID = NA,
  ### order by field \emph{SpatialReferenceID}?
  orderBy_SRSID = NA,
  ### order by field \emph{SRSID}?
  orderBy_SRSName = NA,
  ### order by field \emph{SRSName}?
  orderBy_IsGeographic = NA,
  ### order by field \emph{IsGeographic}?
  orderBy_Notes = NA,
  ### order by field \emph{Notes}?
  db = currentDb(),
  ...
  ### additional arguments passed to \code{\link{selectFromTable}}
) 
{
  arguments <- list(
    select = select,
    select_SpatialReferenceID = select_SpatialReferenceID,
    select_SRSID = select_SRSID,
    select_SRSName = select_SRSName,
    select_IsGeographic = select_IsGeographic,
    select_Notes = select_Notes ,
    where = where,
    where_SpatialReferenceID = where_SpatialReferenceID,
    where_SRSID = where_SRSID,
    where_SRSName = where_SRSName,
    where_IsGeographic = where_IsGeographic,
    where_Notes = where_Notes ,
    orderBy = orderBy,
    orderBy_SpatialReferenceID = orderBy_SpatialReferenceID,
    orderBy_SRSID = orderBy_SRSID,
    orderBy_SRSName = orderBy_SRSName,
    orderBy_IsGeographic = orderBy_IsGeographic,
    orderBy_Notes = orderBy_Notes
  )

  selectFromTable(db, 'SpatialReferences', arguments, ...)
}

# odm_SpeciationCV -------------------------------------------------------------
odm_SpeciationCV <- function # select records from SpeciationCV
### select and filter records from SpeciationCV
(
  where = NULL,
  ### WHERE condition
  where_Term = NA,
  ### condition for field \emph{Term}: Controlled vocabulary for TopicCategory.
  where_Definition = NA,
  ### condition for field \emph{Definition}: Definition of TopicCategory controlled vocabulary term. The definition is optional if the term is self explanatory.
  select = NULL,
  ### fields/expressions to select
  select_Term = NA,
  ### select field \emph{Term}?
  select_Definition = NA,
  ### select field \emph{Definition}?
  orderBy = NULL,
  ### ORDER BY clause of SQL expression
  orderBy_Term = NA,
  ### order by field \emph{Term}?
  orderBy_Definition = NA,
  ### order by field \emph{Definition}?
  db = currentDb(),
  ...
  ### additional arguments passed to \code{\link{selectFromTable}}
) 
{
  arguments <- list(
    select = select,
    select_Term = select_Term,
    select_Definition = select_Definition ,
    where = where,
    where_Term = where_Term,
    where_Definition = where_Definition ,
    orderBy = orderBy,
    orderBy_Term = orderBy_Term,
    orderBy_Definition = orderBy_Definition
  )

  selectFromTable(db, 'SpeciationCV', arguments, ...)
}

# odm_SpeciationCV -------------------------------------------------------------
odm_SpeciationCV <- function # select records from SpeciationCV
### select and filter records from SpeciationCV
(
  where = NULL,
  ### WHERE condition
  where_Term = NA,
  ### condition for field \emph{Term}: Controlled vocabulary for TopicCategory.
  where_Definition = NA,
  ### condition for field \emph{Definition}: Definition of TopicCategory controlled vocabulary term. The definition is optional if the term is self explanatory.
  select = NULL,
  ### fields/expressions to select
  select_Term = NA,
  ### select field \emph{Term}?
  select_Definition = NA,
  ### select field \emph{Definition}?
  orderBy = NULL,
  ### ORDER BY clause of SQL expression
  orderBy_Term = NA,
  ### order by field \emph{Term}?
  orderBy_Definition = NA,
  ### order by field \emph{Definition}?
  db = currentDb(),
  ...
  ### additional arguments passed to \code{\link{selectFromTable}}
) 
{
  arguments <- list(
    select = select,
    select_Term = select_Term,
    select_Definition = select_Definition ,
    where = where,
    where_Term = where_Term,
    where_Definition = where_Definition ,
    orderBy = orderBy,
    orderBy_Term = orderBy_Term,
    orderBy_Definition = orderBy_Definition
  )

  selectFromTable(db, 'SpeciationCV', arguments, ...)
}

# odm_Units --------------------------------------------------------------------
odm_Units <- function # select records from Units
### select and filter records from Units
(
  where = NULL,
  ### WHERE condition
  where_UnitsID = NA,
  ### condition for field \emph{UnitsID}: Unique integer identifier that identifies each unit.
  where_UnitsName = NA,
  ### condition for field \emph{UnitsName}: Full text name of the units.
  where_UnitsType = NA,
  ### condition for field \emph{UnitsType}: Text value that specifies the dimensions of the units.
  where_UnitsAbbreviation = NA,
  ### condition for field \emph{UnitsAbbreviation}: Text abbreviation for the units.
  select = NULL,
  ### fields/expressions to select
  select_UnitsID = NA,
  ### select field \emph{UnitsID}?
  select_UnitsName = NA,
  ### select field \emph{UnitsName}?
  select_UnitsType = NA,
  ### select field \emph{UnitsType}?
  select_UnitsAbbreviation = NA,
  ### select field \emph{UnitsAbbreviation}?
  orderBy = NULL,
  ### ORDER BY clause of SQL expression
  orderBy_UnitsID = NA,
  ### order by field \emph{UnitsID}?
  orderBy_UnitsName = NA,
  ### order by field \emph{UnitsName}?
  orderBy_UnitsType = NA,
  ### order by field \emph{UnitsType}?
  orderBy_UnitsAbbreviation = NA,
  ### order by field \emph{UnitsAbbreviation}?
  db = currentDb(),
  ...
  ### additional arguments passed to \code{\link{selectFromTable}}
) 
{
  arguments <- list(
    select = select,
    select_UnitsID = select_UnitsID,
    select_UnitsName = select_UnitsName,
    select_UnitsType = select_UnitsType,
    select_UnitsAbbreviation = select_UnitsAbbreviation ,
    where = where,
    where_UnitsID = where_UnitsID,
    where_UnitsName = where_UnitsName,
    where_UnitsType = where_UnitsType,
    where_UnitsAbbreviation = where_UnitsAbbreviation ,
    orderBy = orderBy,
    orderBy_UnitsID = orderBy_UnitsID,
    orderBy_UnitsName = orderBy_UnitsName,
    orderBy_UnitsType = orderBy_UnitsType,
    orderBy_UnitsAbbreviation = orderBy_UnitsAbbreviation
  )

  selectFromTable(db, 'Units', arguments, ...)
}

# odm_ValueTypeCV --------------------------------------------------------------
odm_ValueTypeCV <- function # select records from ValueTypeCV
### select and filter records from ValueTypeCV
(
  where = NULL,
  ### WHERE condition
  where_Term = NA,
  ### condition for field \emph{Term}: Controlled vocabulary for ValueType.
  where_Definition = NA,
  ### condition for field \emph{Definition}: Definition of the ValueType controlled vocabulary term. The definition is optional if the term is self explanatory.
  select = NULL,
  ### fields/expressions to select
  select_Term = NA,
  ### select field \emph{Term}?
  select_Definition = NA,
  ### select field \emph{Definition}?
  orderBy = NULL,
  ### ORDER BY clause of SQL expression
  orderBy_Term = NA,
  ### order by field \emph{Term}?
  orderBy_Definition = NA,
  ### order by field \emph{Definition}?
  db = currentDb(),
  ...
  ### additional arguments passed to \code{\link{selectFromTable}}
) 
{
  arguments <- list(
    select = select,
    select_Term = select_Term,
    select_Definition = select_Definition ,
    where = where,
    where_Term = where_Term,
    where_Definition = where_Definition ,
    orderBy = orderBy,
    orderBy_Term = orderBy_Term,
    orderBy_Definition = orderBy_Definition
  )

  selectFromTable(db, 'ValueTypeCV', arguments, ...)
}

# odm_VariableNameCV -----------------------------------------------------------
odm_VariableNameCV <- function # select records from VariableNameCV
### select and filter records from VariableNameCV
(
  where = NULL,
  ### WHERE condition
  where_Term = NA,
  ### condition for field \emph{Term}: Controlled vocabulary for Variable names.
  where_Definition = NA,
  ### condition for field \emph{Definition}: Definition of the VariableName controlled vocabulary term. The definition is optional if the term is self explanatory.
  select = NULL,
  ### fields/expressions to select
  select_Term = NA,
  ### select field \emph{Term}?
  select_Definition = NA,
  ### select field \emph{Definition}?
  orderBy = NULL,
  ### ORDER BY clause of SQL expression
  orderBy_Term = NA,
  ### order by field \emph{Term}?
  orderBy_Definition = NA,
  ### order by field \emph{Definition}?
  db = currentDb(),
  ...
  ### additional arguments passed to \code{\link{selectFromTable}}
) 
{
  arguments <- list(
    select = select,
    select_Term = select_Term,
    select_Definition = select_Definition ,
    where = where,
    where_Term = where_Term,
    where_Definition = where_Definition ,
    orderBy = orderBy,
    orderBy_Term = orderBy_Term,
    orderBy_Definition = orderBy_Definition
  )

  selectFromTable(db, 'VariableNameCV', arguments, ...)
}

# odm_Variables ----------------------------------------------------------------
odm_Variables <- function # select records from Variables
### select and filter records from Variables
(
  where = NULL,
  ### WHERE condition
  where_VariableID = NA,
  ### condition for field \emph{VariableID}: Unique integer identifier for each variable.
  where_VariableCode = NA,
  ### condition for field \emph{VariableCode}: Text code used by the organization that collects the data to identify the variable.
  where_VariableName = NA,
  ### condition for field \emph{VariableName}: Full text name of the variable that was measured, observed, modeled, etc. This should be from the VariableNameCV controlled vocabulary table.
  where_Speciation = NA,
  ### condition for field \emph{Speciation}: Text code used to identify how the data value is expressed (i.e., total phosphorus concentration expressed as P). This should be from the SpeciationCV controlled vocabulary table.
  where_VariableUnitsID = NA,
  ### condition for field \emph{VariableUnitsID}: Integer identifier that references the record in the Units table giving the units of the data values associated with the variable.
  where_SampleMedium = NA,
  ### condition for field \emph{SampleMedium}: The medium in which the sample or observation was taken or made. This should be from the SampleMediumCV controlled vocabulary table.
  where_ValueType = NA,
  ### condition for field \emph{ValueType}: Text value indicating what type of data value is being recorded. This should be from the ValueTypeCV controlled vocabulary table.
  where_IsRegular = NA,
  ### condition for field \emph{IsRegular}: Value that indicates whether the data values are from a regularly sampled time series.
  where_TimeSupport = NA,
  ### condition for field \emph{TimeSupport}: Numerical value that indicates the time support (or temporal footprint) of the data values. 0 is used to indicate data values that are instantaneous. Other values indicate the time over which the data values are implicitly or explicitly averaged or aggregated.
  where_TimeUnitsID = NA,
  ### condition for field \emph{TimeUnitsID}: Integer identifier that references the record in the Units table giving the Units of the time support. If TimeSupport is 0, indicating an instantaneous observation, a unit needs to still be given for completeness, although it is somewhat arbitrary.
  where_DataType = NA,
  ### condition for field \emph{DataType}: Text value that identifies the data values as one of several types from the DataTypeCV controlled vocabulary table.
  where_GeneralCategory = NA,
  ### condition for field \emph{GeneralCategory}: General category of the data values from the GeneralCategoryCV controlled vocabulary table.
  where_NoDataValue = NA,
  ### condition for field \emph{NoDataValue}: Numeric value used to encode no data values for this variable.
  select = NULL,
  ### fields/expressions to select
  select_VariableID = NA,
  ### select field \emph{VariableID}?
  select_VariableCode = NA,
  ### select field \emph{VariableCode}?
  select_VariableName = NA,
  ### select field \emph{VariableName}?
  select_Speciation = NA,
  ### select field \emph{Speciation}?
  select_VariableUnitsID = NA,
  ### select field \emph{VariableUnitsID}?
  select_SampleMedium = NA,
  ### select field \emph{SampleMedium}?
  select_ValueType = NA,
  ### select field \emph{ValueType}?
  select_IsRegular = NA,
  ### select field \emph{IsRegular}?
  select_TimeSupport = NA,
  ### select field \emph{TimeSupport}?
  select_TimeUnitsID = NA,
  ### select field \emph{TimeUnitsID}?
  select_DataType = NA,
  ### select field \emph{DataType}?
  select_GeneralCategory = NA,
  ### select field \emph{GeneralCategory}?
  select_NoDataValue = NA,
  ### select field \emph{NoDataValue}?
  orderBy = NULL,
  ### ORDER BY clause of SQL expression
  orderBy_VariableID = NA,
  ### order by field \emph{VariableID}?
  orderBy_VariableCode = NA,
  ### order by field \emph{VariableCode}?
  orderBy_VariableName = NA,
  ### order by field \emph{VariableName}?
  orderBy_Speciation = NA,
  ### order by field \emph{Speciation}?
  orderBy_VariableUnitsID = NA,
  ### order by field \emph{VariableUnitsID}?
  orderBy_SampleMedium = NA,
  ### order by field \emph{SampleMedium}?
  orderBy_ValueType = NA,
  ### order by field \emph{ValueType}?
  orderBy_IsRegular = NA,
  ### order by field \emph{IsRegular}?
  orderBy_TimeSupport = NA,
  ### order by field \emph{TimeSupport}?
  orderBy_TimeUnitsID = NA,
  ### order by field \emph{TimeUnitsID}?
  orderBy_DataType = NA,
  ### order by field \emph{DataType}?
  orderBy_GeneralCategory = NA,
  ### order by field \emph{GeneralCategory}?
  orderBy_NoDataValue = NA,
  ### order by field \emph{NoDataValue}?
  db = currentDb(),
  ...
  ### additional arguments passed to \code{\link{selectFromTable}}
) 
{
  arguments <- list(
    select = select,
    select_VariableID = select_VariableID,
    select_VariableCode = select_VariableCode,
    select_VariableName = select_VariableName,
    select_Speciation = select_Speciation,
    select_VariableUnitsID = select_VariableUnitsID,
    select_SampleMedium = select_SampleMedium,
    select_ValueType = select_ValueType,
    select_IsRegular = select_IsRegular,
    select_TimeSupport = select_TimeSupport,
    select_TimeUnitsID = select_TimeUnitsID,
    select_DataType = select_DataType,
    select_GeneralCategory = select_GeneralCategory,
    select_NoDataValue = select_NoDataValue ,
    where = where,
    where_VariableID = where_VariableID,
    where_VariableCode = where_VariableCode,
    where_VariableName = where_VariableName,
    where_Speciation = where_Speciation,
    where_VariableUnitsID = where_VariableUnitsID,
    where_SampleMedium = where_SampleMedium,
    where_ValueType = where_ValueType,
    where_IsRegular = where_IsRegular,
    where_TimeSupport = where_TimeSupport,
    where_TimeUnitsID = where_TimeUnitsID,
    where_DataType = where_DataType,
    where_GeneralCategory = where_GeneralCategory,
    where_NoDataValue = where_NoDataValue ,
    orderBy = orderBy,
    orderBy_VariableID = orderBy_VariableID,
    orderBy_VariableCode = orderBy_VariableCode,
    orderBy_VariableName = orderBy_VariableName,
    orderBy_Speciation = orderBy_Speciation,
    orderBy_VariableUnitsID = orderBy_VariableUnitsID,
    orderBy_SampleMedium = orderBy_SampleMedium,
    orderBy_ValueType = orderBy_ValueType,
    orderBy_IsRegular = orderBy_IsRegular,
    orderBy_TimeSupport = orderBy_TimeSupport,
    orderBy_TimeUnitsID = orderBy_TimeUnitsID,
    orderBy_DataType = orderBy_DataType,
    orderBy_GeneralCategory = orderBy_GeneralCategory,
    orderBy_NoDataValue = orderBy_NoDataValue
  )

  selectFromTable(db, 'Variables', arguments, ...)
}

# odm_VerticalDatumCV ----------------------------------------------------------
odm_VerticalDatumCV <- function # select records from VerticalDatumCV
### select and filter records from VerticalDatumCV
(
  where = NULL,
  ### WHERE condition
  where_Term = NA,
  ### condition for field \emph{Term}: Controlled vocabulary for VerticalDatum.
  where_Definition = NA,
  ### condition for field \emph{Definition}: Definition of the VerticalDatum controlled vocabulary. The definition is optional if the term is self explanatory.
  select = NULL,
  ### fields/expressions to select
  select_Term = NA,
  ### select field \emph{Term}?
  select_Definition = NA,
  ### select field \emph{Definition}?
  orderBy = NULL,
  ### ORDER BY clause of SQL expression
  orderBy_Term = NA,
  ### order by field \emph{Term}?
  orderBy_Definition = NA,
  ### order by field \emph{Definition}?
  db = currentDb(),
  ...
  ### additional arguments passed to \code{\link{selectFromTable}}
) 
{
  arguments <- list(
    select = select,
    select_Term = select_Term,
    select_Definition = select_Definition ,
    where = where,
    where_Term = where_Term,
    where_Definition = where_Definition ,
    orderBy = orderBy,
    orderBy_Term = orderBy_Term,
    orderBy_Definition = orderBy_Definition
  )

  selectFromTable(db, 'VerticalDatumCV', arguments, ...)
}
